RELEVANCE_KEYWORDS = [
    "data analytics",
    "data engineering",
    "data warehouse",
    "data management",
    "data governance",
    "data visualization",
    "data pipeline",
    "data integration",
    "data migration",
    "data quality",
    "ETL",
    "business intelligence",
    "artificial intelligence",
    "machine learning",
    "AI",
    "predictive",
    "natural language",
    "generative",
    "LLM",
    "deep learning",
    "NLP",
    "digital transformation",
    "IT modernization",
    "cloud migration",
    "legacy modernization",
    "platform migration",
    "automation",
    "robotic process",
    "RPA",
    "workflow automation",
    "dashboard",
    "reporting",
    "BI",
]
